# Generated by Django 3.2.8 on 2023-04-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категории')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Изображение категории')),
                ('url', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название материала')),
                ('image', models.ImageField(upload_to='image_Material/', verbose_name='Изображение')),
                ('quantity', models.CharField(max_length=10, verbose_name='Товар измеряется в:')),
                ('code', models.CharField(max_length=10, verbose_name='Артикул')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product_categories', verbose_name='Категория')),
            ],
        ),
    ]
